### ISSUE TITLE
nextflow required version

### ISSUE THREAD

**Issue by JHYSiu** [salzman-lab/nomad#44]
Hi. 

Just wanted to clarify pre-reqs. 

Based on the intro prereq doc, it said that Install nextflow req was >=20.04.0. Is that a typo or have I accidentally accessed a dev version? It appears >=21.04.0 is required when I try it out. Thanks!

**Comment by TavorB** [comment]
Hi Jacqueline,

Thanks for reaching out! I'll check on the nextflow requirements, but I would strongly recommend using our updated codebase here: https://github.com/refresh-bio/SPLASH . We've worked with some amazing collaborators to make a highly efficient and parallelized implementation, with some more powerful statistical tools. Please let us know if you have any issues with it, or want to discuss how SPLASH could be best be used in your case.

Best,
Tavor

**Comment by JHYSiu** [comment]
Thanks!
